value1 = int(input("Integer: : "))
print("Value1 : {} , Type1 : {} ".format(value1,type(value1)))
value2 = input("String : ")
print("Value2 : {} , Type2 : {} ".format(value2,type(value2)))
value3 = float(input("Float : "))
print("Value3 : {} , Type3 : {} ".format(value3,type(value3)))
value4 = int(input("Integer : "))
print("Value4 : {} , Type4 : {} ".format(value4,type(value4)))
value5 = float(input("Float : ") )
print("Value5 : {} , Type5 : {} ".format(value5,type(value5)))